# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\nvectorbase\"A\n\x0bIndexConfig\x12\t\n\x01M\x18\x01 \x01(\x05\x12\x17\n\x0f\x65\x66_construction\x18\x02 \x01(\x05\x12\x0e\n\x06metric\x18\x03 \x01(\t\"\x95\x01\n\x0cVectorRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x38\n\x08metadata\x18\x03 \x03(\x0b\x32&.vectorbase.VectorRecord.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\rSegmentConfig\x12\x1f\n\x17max_vectors_per_segment\x18\x01 \x01(\x05\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VECTORRECORD_METADATAENTRY._options = None
  _VECTORRECORD_METADATAENTRY._serialized_options = b'8\001'
  _globals['_INDEXCONFIG']._serialized_start=28
  _globals['_INDEXCONFIG']._serialized_end=93
  _globals['_VECTORRECORD']._serialized_start=96
  _globals['_VECTORRECORD']._serialized_end=245
  _globals['_VECTORRECORD_METADATAENTRY']._serialized_start=198
  _globals['_VECTORRECORD_METADATAENTRY']._serialized_end=245
  _globals['_SEGMENTCONFIG']._serialized_start=247
  _globals['_SEGMENTCONFIG']._serialized_end=308
# @@protoc_insertion_point(module_scope)
