# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectordb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\nvectorbase\x1a\x0c\x63ommon.proto\"i\n\rInsertRequest\x12)\n\x07vectors\x18\x01 \x03(\x0b\x32\x18.vectorbase.VectorRecord\x12-\n\x0cindex_config\x18\x02 \x01(\x0b\x32\x17.vectorbase.IndexConfig\"K\n\x0eInsertResponse\x12\x0b\n\x03lsn\x18\x01 \x01(\x03\x12\x16\n\x0einserted_count\x18\x02 \x01(\x05\x12\x14\n\x0cinserted_ids\x18\x03 \x03(\x03\"<\n\rSearchRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\x12\n\n\x02\x65\x66\x18\x03 \x01(\x05\"\x97\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x38\n\x08metadata\x18\x03 \x03(\x0b\x32&.vectorbase.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\x0eSearchResponse\x12)\n\x07results\x18\x01 \x03(\x0b\x32\x18.vectorbase.SearchResult\x12\x15\n\rquery_time_ms\x18\x02 \x01(\x02\"\x1c\n\rDeleteRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x03\"4\n\x0e\x44\x65leteResponse\x12\x0b\n\x03lsn\x18\x01 \x01(\x03\x12\x15\n\rdeleted_count\x18\x02 \x01(\x05\"\x0e\n\x0cStatsRequest\"\x81\x01\n\rStatsResponse\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x03\x12\x14\n\x0cnum_segments\x18\x02 \x01(\x05\x12\x1b\n\x13num_sealed_segments\x18\x03 \x01(\x05\x12\x13\n\x0b\x63urrent_lsn\x18\x04 \x01(\x03\x12\x11\n\tmemory_mb\x18\x05 \x01(\x02\x32\x8e\x02\n\x08VectorDB\x12?\n\x06Insert\x12\x19.vectorbase.InsertRequest\x1a\x1a.vectorbase.InsertResponse\x12?\n\x06Search\x12\x19.vectorbase.SearchRequest\x1a\x1a.vectorbase.SearchResponse\x12?\n\x06\x44\x65lete\x12\x19.vectorbase.DeleteRequest\x1a\x1a.vectorbase.DeleteResponse\x12?\n\x08GetStats\x12\x18.vectorbase.StatsRequest\x1a\x19.vectorbase.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHRESULT_METADATAENTRY._options = None
  _SEARCHRESULT_METADATAENTRY._serialized_options = b'8\001'
  _globals['_INSERTREQUEST']._serialized_start=44
  _globals['_INSERTREQUEST']._serialized_end=149
  _globals['_INSERTRESPONSE']._serialized_start=151
  _globals['_INSERTRESPONSE']._serialized_end=226
  _globals['_SEARCHREQUEST']._serialized_start=228
  _globals['_SEARCHREQUEST']._serialized_end=288
  _globals['_SEARCHRESULT']._serialized_start=291
  _globals['_SEARCHRESULT']._serialized_end=442
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=395
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=442
  _globals['_SEARCHRESPONSE']._serialized_start=444
  _globals['_SEARCHRESPONSE']._serialized_end=526
  _globals['_DELETEREQUEST']._serialized_start=528
  _globals['_DELETEREQUEST']._serialized_end=556
  _globals['_DELETERESPONSE']._serialized_start=558
  _globals['_DELETERESPONSE']._serialized_end=610
  _globals['_STATSREQUEST']._serialized_start=612
  _globals['_STATSREQUEST']._serialized_end=626
  _globals['_STATSRESPONSE']._serialized_start=629
  _globals['_STATSRESPONSE']._serialized_end=758
  _globals['_VECTORDB']._serialized_start=761
  _globals['_VECTORDB']._serialized_end=1031
# @@protoc_insertion_point(module_scope)
