# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vectordb_pb2 as vectordb__pb2


class VectorDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/vectorbase.VectorDB/Insert',
                request_serializer=vectordb__pb2.InsertRequest.SerializeToString,
                response_deserializer=vectordb__pb2.InsertResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/vectorbase.VectorDB/Search',
                request_serializer=vectordb__pb2.SearchRequest.SerializeToString,
                response_deserializer=vectordb__pb2.SearchResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/vectorbase.VectorDB/Delete',
                request_serializer=vectordb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteResponse.FromString,
                )
        self.GetStats = channel.unary_unary(
                '/vectorbase.VectorDB/GetStats',
                request_serializer=vectordb__pb2.StatsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.StatsResponse.FromString,
                )


class VectorDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=vectordb__pb2.InsertRequest.FromString,
                    response_serializer=vectordb__pb2.InsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vectordb__pb2.SearchRequest.FromString,
                    response_serializer=vectordb__pb2.SearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=vectordb__pb2.DeleteRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=vectordb__pb2.StatsRequest.FromString,
                    response_serializer=vectordb__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectorbase.VectorDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorbase.VectorDB/Insert',
            vectordb__pb2.InsertRequest.SerializeToString,
            vectordb__pb2.InsertResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorbase.VectorDB/Search',
            vectordb__pb2.SearchRequest.SerializeToString,
            vectordb__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorbase.VectorDB/Delete',
            vectordb__pb2.DeleteRequest.SerializeToString,
            vectordb__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vectorbase.VectorDB/GetStats',
            vectordb__pb2.StatsRequest.SerializeToString,
            vectordb__pb2.StatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
